##### 1、0-1背包问题

In [16]:
### 0-1背包问题

import numpy as np

def main():
    print('begin')
    n = int(input('输入物品种类：'))
    
    s = int(input('输入背包容量:'))
    memory = []
    for i in range(n):
        
        print('输入物品%d的重量:'%i)
        w = int(input())
        print('输入物品%d的价值:'%i)
        v = int(input())
        memory.append((w, v)) # memory是一个列表，每个元素是一个元祖，元组的第一个值是重量，第二个值是价值
    print(len(memory))
    matrix, result = KnapSack(n, s, memory)
    print(matrix)
    print(result)

def KnapSack(n, s, memory):
    array = np.zeros((n+1, s+1), dtype=np.int32) # 多创造一个第零行和第零列
    for i in range(1, n+1):
        for j in range(1, s+1):
            if j < memory[i-1][0]:  # 当前容量装不下第i个物品
                array[i][j] = array[i-1][j]
            else:
                array[i][j] = max(memory[i-1][1]+array[i][j-memory[i-1][0]], array[i-1][j])

    return array, array[n][s]

main()

begin


输入物品种类： 4
输入背包容量: 10


输入物品0的重量:


 5


输入物品0的价值:


 10


输入物品1的重量:


 4


输入物品1的价值:


 40


输入物品2的重量:


 6


输入物品2的价值:


 30


输入物品3的重量:


 3


输入物品3的价值:


 50


4
[[  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  10  10  10  10  10  20]
 [  0   0   0   0  40  40  40  40  80  80  80]
 [  0   0   0   0  40  40  40  40  80  80  80]
 [  0   0   0  50  50  50 100 100 100 150 150]]
150


##### 2、多重背包问题

In [19]:
def main():
    n = int(input('输入物品种类:'))
    m = int(input('输入背包容量:'))
    memory = [] # 用来存储物品重量和对应价值
    for i in range(n):
        print('输入物品%d的重量:'%i)
        w = int(input())
        print('输入物品%d的价值:'%i)
        v = int(input())
        memory.append((w,v))
    print(len(memory))
    result = bag_multi(n, m, memory)
    print("背包最大价值为:"+str(result))
    
def bag_multi(n, m, memory):
    result = [0] * (m+1) # result表示，当不存入物品的时候，容量分别为1到m所带来的价值
    for i in range(n):
        # 存第i个物品,共n个物品，从0到n-1
        for j in range(1,m+1):
            # 当容量为j+1的时候,容量得从1到m
            if (j >= memory[i][0]):
                result[j] = max(result[j], result[j-memory[i][0]] + memory[i][1])
            else:
                result[j] = result[j]
    return result[m-1]

main()
        
        

输入物品种类: 4
输入背包容量: 10


输入物品0的重量:


 5


输入物品0的价值:


 10


输入物品1的重量:


 4


输入物品1的价值:


 40


输入物品2的重量:


 6


输入物品2的价值:


 30


输入物品3的重量:


 3


输入物品3的价值:


 50


4
背包最大价值为:150


##### 3、0-1背包问题的一维数组解法

In [20]:
def main():
    n = int(input('输入物品种类:'))
    m = int(input('输入背包容量:'))
    memory = [] # 用来存储物品重量和对应价值
    for i in range(n):
        print('输入物品%d的重量:'%i)
        w = int(input())
        print('输入物品%d的价值:'%i)
        v = int(input())
        memory.append((w,v))
    print(len(memory))
    result = bag_multi(n, m, memory)
    print("背包最大价值为:"+str(result))

    
def bag_multi(n, m, memory):
    result = [0] * (m+1) # result表示，当不存入物品的时候，容量分别为1到m所带来的价值
    for i in range(n):
        # 存第i个物品
        for j in range(1,m+1)[::-1]:
            if j >= memory[i][0]:
                # 当前的容量能够装入物品i
                result[j] = max(result[j], result[j-memory[i][0]] + memory[i][1])
            else:
                result[j] = result[j]
                
    return result[m-1]
                
            
main()    

输入物品种类: 4
输入背包容量: 10


输入物品0的重量:


 5


输入物品0的价值:


 10


输入物品1的重量:


 4


输入物品1的价值:


 40


输入物品2的重量:


 6


输入物品2的价值:


 30


输入物品3的重量:


 3


输入物品3的价值:


 50


4
背包最大价值为:90


##### 4、多重背包问题

In [ ]:
# 多重背包问题限定了一种物品的个数，解决这个问题，只需要把它转化为0-1背包问题就可以。